deploy:
  provider: heroku
  api_key:
    secure: C5aDCY3ST4oLXaklJNnsmPZIB7apBN5Mjhsx6zeoUjW3K7DDwC7ZfU9lW48MNF9LPY/daSI4+AdBJF5aat0OCCRDwrK3Qe6KIlz4M/TftYyR8wI0bU/g43mKze9eAfjIM0wFR9LmAFp/uWGB91M9eXC6DRwLq5F/wtskZEM/b5wm8do9mACdsZEs9OgtM8QHoEPo4MMVR+xkyrIYjgxkKC5HnBPLuxMcCgVtZd2kK8ckrZBZhglR38DyYlm+hPSvmPdUk6Zu7wJ3e75PKBcaa2Y7bduMoy0qF0KP19z5Sfbezw/r+0zdLhQ98cRRyaO6V1kgAKbM6olwai3kFLLvI9/r502OakQvloLXbRByMGdlBno5LYylRxZbeAZs45Y32km2Den7jCqEfRVe7JTVAOMuJ1zRBwR0CS6r5gEcnRp+E8D4q6xW1VnpBEDccXknkqt/KFj7loTUGAVXMs7CcBY54UZWBuOj3IWan82h5V6v3CiqAGhXmsYwAXxwEDae43iVbK6t0iRQD5AI5/1u7x+RCnk75W4L2jD3LaYsmQEdB9FaPYr9ajIp/0siVUnMVap5xe0X4NC9uoJVN1HQ1e6Qd+FjPIQPQ2C7IrH19ifHKC1KbASCZyT4HY+1vguUa5BElEFBlqoqnsbgHXzJs1RAL4S3SsDdxYt5Wi5kQLY=
  app: rocky-reef-27804
  on:
    repo: trcrkrn/blog-app
